name: CI/CD Pipeline
on:
    push:
        branches: [ $default-branch, main ]
    pull_request:
        branches: [ $default-branch, main ]

jobs:
    # test:
    #   runs-on: ubuntu-latest

    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Install dependencies
    #       run: |
    #         python -m pip install --upgrade pip
    #         pip install pytest
    #         pip install -r requirements.txt
    #     - name: Test with pytest
    #       run: |
    #         python -m pytest

    # local-dockerhub-push:
    #   # https://docs.docker.com/reference/cli/docker/login/#password-stdin
    #   needs: test
    #   runs-on: ubuntu-latest

    #   steps:
    #     - uses: actions/checkout@v4
    #     - name: Login to Dockerhub via CLI
    #       env: 
    #         DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
    #         DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PAT }}
    #       run: echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
    #     - name: Build and push image
    #       env:
    #         DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
    #       run: |
    #         docker build -t "$DOCKERHUB_REPO:v1" .
    #         docker push "$DOCKERHUB_REPO:v1"
    
    vps-dockerhub-pull-and-build:
      # needs: local-dockerhub-push
      runs-on: ubuntu-latest

      # 1. SSH into VPS
      # 2. Pull from Dockerhub onto VPS
      # 3. Build and run image
      steps:
        # - uses: actions/checkout@v4
        - name: SSH into VPS
          env:
            VPS_SSH_HOST: ${{ secrets.VPS_HOST }}
            VPS_SSH_KEY: ${{ secrets.VPS_SSH }}
            VPS_SSH_USER: ${{ secrets.VPS_USER }}
            DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PAT }}
            DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
          
          # Temporarily write the SSH key to a file, use that to SSH in, execute commands, then remove the file
          run: |
            echo "$VPS_SSH_KEY" > key.temp
            chmod 600 key.temp
            ssh "$VPS_SSH_USER@$VPS_SSH_HOST" -i key.temp << EOF
                echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
                docker pull "$DOCKERHUB_REPO:v1"
                docker run "$DOCKERHUB_REPO:v1"
            EOF

            rm key.temp