name: CI/CD Pipeline
on:
    push:
        branches: [ $default-branch, main ]
    pull_request:
        branches: [ $default-branch, main ]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
            pip install -r requirements.txt
        - name: Test with pytest
          run: |
            python -m pytest
    dockerhub-push:
      # https://docs.docker.com/reference/cli/docker/login/#password-stdin
      needs: test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Login to Dockerhub via CLI
          env:
            DOCKERHUB_USER: 
            DOCKERHUB_PASS: 
          run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        - name: Build and push image
          run: |
            docker build -t tdishman/cs333_final:v1 .
            docker push tdishman/cs333_final:v1
          
