name: Run Tests
on:
    push:
        branches: [ $default-branch, main ]
    pull_request:
        branches: [ $default-branch, main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install -r requirements.txt
            - name: Test with pytest
              run: |
                python -m pytest